import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["greek"] });
export const metadata = {
  title: "Hendriansyah Rizky Setiawan - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="QcbyU9ulSTslAaeS9j0MmZGr0ZdAR7c3RvstcFuKYsk" />
        <link rel="icon" href="/images/logo-hr.png" sizes="any" />
      </head>
      <body className={inter.className}>{children}
      </body>
    </html>
  );
}
